name: CrazyWeather
main: de.st_ddt.crazyweather.CrazyWeather
author: ST-DDT
version: 5.2.2
website: http://dev.bukkit.org/server-mods/crazycore/
# requires CrazyCore v10.7.3 or later
depend: [CrazyCore]
commands:
  weather: 
    description: Change weather
    usage: /<command> <[weather:]Weather> [world:World] [static:True/False] [load:True/False] [duration:Ticks]
  sun:
    description: Cast sun
    usage: /<command> [duration:Ticks]
  rain:
    description: Cast rain
    usage: /<command> [duration:Ticks]
  thunderrain:
    description: Cast thunderstorm
    usage: /<command> [duration:Ticks]
    aliases: [storm]
  strike:
    description: Cast a lighting strike on target.
    usage: /<command>|/<command> player
    aliases: [thunder]
  crazyweather:
    description: Plugin Main Menu
    usage: /<command> [Subcommands...]
permissions:
  crazyweather.*:
    description: Access to all commands
    default: false
    children:
      crazyweather.weather.*: true
      crazyweather.weather.sun: true
      crazyweather.weather.rain: true
      crazyweather.weather.thunder: true
      crazyweather.weather.thunderain: true
      crazyweather.thunder.*: true
      crazyweather.thunder: true
      crazyweather.thunder.player: true
      crazyweather.thunder.tool: true
      crazyweather.mode: true
# use crazyweather.<World>.weather.xxx to allow it for a single world
  crazyweather.weather.*:
    description: Allows every weather change on every world.
    default: op
    children:
      crazyweather.weather.sun: true
      crazyweather.weather.rain: true
      crazyweather.weather.thunder: true
      crazyweather.weather.thunderain: true
  crazyweather.weather.sun: 
    description: Allows sunny weather change on every world.
    default: op
  crazyweather.weather.rain: 
    description: Allows rainy weather change on every world.
    default: op
  crazyweather.weather.thunder: 
    description: Allows thunder weather change on every world.
    default: op
  crazyweather.weather.thunderain: 
    description: Allows thunderrain weather change on every world.
    default: op
# use crazyweather.<World>.thunder.xxx to allow it for a single world
  crazyweather.thunder.*:
    description: Allows every kind of lightningstrike on every world.
    default: op
    children:
      crazyweather.thunder: true
      crazyweather.thunder.player: true
      crazyweather.thunder.tool: true
  crazyweather.thunder: 
    description: Allows thunderstrikes via command on every world-
    default: op
  crazyweather.thunder.player: 
    description: Allows thunderstrikes on a player via command on every world.
    default: op
    children: 
      crazyweather.thunder: true
  crazyweather.thunder.tool: 
    description: Allows thunderstrikes via tool on every world.
    default: op
  crazyweather.mode: 
    description: Allows changing plugin options.
    default: op