name: CrazyLogin
main: de.st_ddt.crazylogin.CrazyLogin
author: ST-DDT
version: 7.21
website: http://dev.bukkit.org/server-mods/crazylogin/
# requires CrazyCore v10.7.1 or later
depend: [CrazyCore]
description: >
            CrazyLogin protect your server with passwords and many usefully features.
commands:
  login:
    description: Login using a password
    usage: /<command> <Password...>
    aliases: [l]
  loginonce:
    description: Login using a password and enable auto logout
    usage: /<command> <Password...>
    aliases: [l1,lonce]
  adminlogin:
    description: Login using an admin account and enable auto logout
    usage: /<command> <Admin> <AdminPassword...>
  tokenlogin:
    description: Login using a token and enable auto logout
    usage: /<command> <Token>
  autologout:
    description: Enable auto logout
    usage: /<command>
  logout:
    description: Logout and leave server
    usage: /<command>
  register:
    description: Create/Change password
    usage: /<command> <new Password>
    aliases: [changepw,chgpw,changepassword]
  crazylogin:
    description: Plugin Main Menu
    usage: /<command> password <new Password>
    aliases: [cl,clogin]
permissions:
  crazylogin.*:
    description: Access to all permissions belonging to this plugin.
    default: op
    children:
      crazycore.protectedplayer: true
      crazylogin.adminlogin: true
      crazylogin.blockadminlogin: true
      crazylogin.blocktokenlogin: true
      crazylogin.bypasshideplayer: true
      crazylogin.commands: true
      crazylogin.dropolddata: true
      crazylogin.ensureregistration: true
      crazylogin.generatetoken: true
      crazylogin.help: true
      crazylogin.info: true
      crazylogin.logger: true
      crazylogin.login.channel: true
      crazylogin.login.command: true
      crazylogin.logout.channel: true
      crazylogin.logout.command: true
      crazylogin.mode: true
      crazylogin.mode.*: true
      crazylogin.player.create: true
      crazylogin.player.delete: true
      crazylogin.player.delete.protected: true
      crazylogin.player.detachip: true
      crazylogin.player.info.other: true
      crazylogin.player.info.self: true
      crazylogin.player.list: true
      crazylogin.player.password: true
      crazylogin.player.password.protected: true
      crazylogin.player.reverify: true
      crazylogin.register.channel: true
      crazylogin.register.command: true
      crazylogin.reload: true
      crazylogin.reload.*: true
      crazylogin.reload.config: true
      crazylogin.reload.database: true
      crazylogin.requirepassword: true
      crazylogin.save: true
      crazylogin.saveloginlocation: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnloginfailure: true
      crazylogin.warnsession: true
  crazylogin.adminlogin:
    description: Allow admins to login as another player.
    default: op
    children:
      crazylogin.requirepassword: true
  crazylogin.blockadminlogin:
    description: Block admins logins to this account.
    default: false
  crazylogin.blocktokenlogin:
    description: Block token logins to this account.
    default: false
  crazylogin.bypasshideplayer:
    description: Show all players to this player even if they are hidden due to hidePlayer option.
    default: op
  crazylogin.commands:
    description: Allow viewing and editing command whitelist.
    default: op
  crazylogin.dropolddata:
    description: Allow deleting old accounts.
    default: op
    children:
      crazylogin.warndelete: true
  crazylogin.ensureregistration:
    description: This player can always register an account.
    default: op
    children:
      crazylogin.register.channel: true
      crazylogin.register.command: true
  crazylogin.generatetoken:
    description: Allow creations of tokens to login as another player.
    default: op
    children:
      crazylogin.requirepassword: true
  crazylogin.help:
    description: Allow accessing the plugin help.
    default: op
  crazylogin.info:
    description: Allow showing information about this plugin.
    default: op
  crazylogin.logger:
    description: Allow configuring the plugin logger.
    default: op
  crazylogin.login.channel:
    description: Allow players to login via pluginChannel.
    default: true
  crazylogin.login.command:
    description: Allow players to login via command.
    default: true
  crazylogin.logout.channel:
    description: Allow players to logout via pluginChannel.
    default: true
  crazylogin.logout.command:
    description: Allow players to logout via command.
    default: true
  crazylogin.mode:
    description: Allow changing plugin modes.
    default: op
  crazylogin.mode.*:
    description: Allow changing plugin all modes.
    default: op
  crazylogin.player.create:
    description: Allow creating player data.
    default: op
  crazylogin.player.delete:
    description: Allow deleting a player's account.
    default: op
  crazylogin.player.delete.protected:
    description: Allow deleting a protected player's account.
    default: op
    children:
      crazylogin.player.delete: true
  crazylogin.player.detachip:
    description: Allow removing an IP from a player.
    default: op
  crazylogin.player.info.other:
    description: Allow viewing playerinfo for other players.
    default: op
  crazylogin.player.info.self:
    description: Allow viewing own playerinfo.
    default: true
  crazylogin.player.list:
    description: Allow viewing all players accounts.
    default: op
  crazylogin.player.password:
    description: Allow changing a player's password.
    default: op
  crazylogin.player.password.protected:
    description: Allow changing a protected player's password.
    default: op
    children:
      crazylogin.player.password: true
  crazylogin.player.reverify:
    description: Allow forcing a player to login again.
    default: op
  crazylogin.register.channel:
    description: Allow players to create a password via pluginChannel.
    default: true
  crazylogin.register.command:
    description: Allow players to create a password via command.
    default: true
  crazylogin.reload:
    description: Allow reloading the plugin.
    default: op
  crazylogin.reload.*:
    description: Allow reloading the entire plugin.
    default: op
  crazylogin.reload.config:
    description: Allow reloading the config of this plugin.
    default: op
  crazylogin.reload.database:
    description: Allow reloading the database of this plugin.
    default: op
  crazylogin.requirepassword:
    description: Force this player to create a password.
    default: op
  crazylogin.save:
    description: Allow saving the plugin.
    default: op
  crazylogin.saveloginlocation:
    description: Allow viewing and changing save login locations.
    default: op
  crazylogin.warncommandexploits:
    description: Get informed if someone tries to execute a none whitelisted command.
    default: op
  crazylogin.warndatabase:
    description: Get informed if database connection fails
    default: op
  crazylogin.warndelete:
    description: Get informed if old accounts are deleted (via admincommands)
    default: op
  crazylogin.warnloginfailure:
    description: Get informed if someone fails to login
    default: op
  crazylogin.warnsession:
    description: Get informed if somebody tries to login from another location.
    default: op