name: CrazyLoginRank
main: de.st_ddt.crazyloginrank.CrazyLoginRank
author: ST-DDT
version: 0.2.2
website: http://dev.bukkit.org/server-mods/crazycore/pages/crazy-login-rank/
# requires CrazyCore v10.7.1 or later
depend: [CrazyCore]
description: >
            CrazyLoginRank allow your favorite players to connect to your server.
commands:
  rank:
    description: get/set a players rank
    usage: /<command> [Player [Rank]]
    aliases: [crank,crazyrank]
  crazyloginrank:
    description: Plugin Main Menu
    usage: /<command>
    aliases: [clr]
permissions:
  crazyloginrank.*:
    description: Access to all commands
    default: false
    children:
      crazyloginrank.admin: true
      crazyloginrank.list: true
  crazyloginrank.admin:
    description: Allow changingplayer ranks
    default: op
    children: 
      crazyloginrank.list: true
  crazyloginrank.list:
    description: List all player ranks.
    default: op