name: CrazyPromoter
main: de.st_ddt.crazypromoter.CrazyPromoter
author: ST-DDT
version: 2.12.2
website: http://dev.bukkit.org/server-mods/crazypromoter/
# requires CrazyCore v10.7.1 or later
depend: [CrazyCore]
softdepend: [CrazyOnline,CrazyLogin]
description: >
            Add custom promotion scripts to your server.
commands:
  promotioncheck:
    description: Check promotion status
    usage: /<command> [Player]
  crazypromoter:
    descrition: Plugin Main Menu
    usage: /<command> ...
permissions:
  crazypromoter.check:
    description: Check promotions status.
    default: op
    children: 
      crazypromoter.check.self: true
      crazypromoter.check.other: true
  crazypromoter.check.self:
    description: Check your promotion status.
    default: true
  crazypromoter.check.other:
    description: Check other players promotion status.
    default: op
