name: CrazyOnline
main: de.st_ddt.crazyonline.CrazyOnline
author: ST-DDT
version: 7.1.4
website: http://dev.bukkit.org/server-mods/crazyonline/
# requires CrazyCore v10.7.1 or later
depend: [CrazyCore]
commands:
  pinfo:
    description: Show information about player
    usage: /<command> [Player]
  ptop10:
    description: Show Top10 online players
    usage: /<command> [Page] [> Pipe]
  ponlines:
    description: Show information about online player
    usage: /<command>
    aliases: [list]
  psince:
    description: Shows players who logged in since Date (yyyy.MM.dd HH:mm:ss)
    usage: /<command> [Date [Time]]
  pbefore:
    description: Shows players who did not logged in since Date (yyyy.MM.dd HH:mm:ss)
    usage: /<command> [Date [Time]]
  crazyonline:
    description: Plugin Main Menu
    usage: /<command> [subcommands]
    aliases: [co]
permissions:
  crazyonline.*:
    description: Access to all commands
    default: false
    children:
      crazyonline.admin: true
      crazyonline.online: true
      crazyonline.since: true
      crazyonline.since.auto: true
      crazyonline.before: true
      crazyonline.top10: true
      crazyonline.mode: true
      crazyonline.list: true
      crazyonline.player.info: true
      crazyonline.player.info.self: true
      crazyonline.player.info.other: true
      crazyonline.player.delete: true
  crazyonline.admin:
    description: Access to admin commands
    default: op
    children:
      crazyonline.online: true
      crazyonline.since: true
      crazyonline.since.auto: true
      crazyonline.before: true
      crazyonline.top10: true
      crazyonline.mode: true
      crazyonline.list: true
      crazyonline.player.info: true
      crazyonline.player.info.self: true
      crazyonline.player.info.other: true
      crazyonline.player.delete: true
  crazyonline.info.self:
    description: Show information about yourself
    default: true
  crazyonline.info.other:
    description: Show information about player
    default: op
  crazyonline.online:
    description: Show information about online player
    default: op
  crazyonline.top10:
    description: Show Top10 online players.
    default: op
  crazyonline.since:
    description: Shows which players has been online
    default: op
  crazyonline.since.auto:
    description: Shows which players has been online on login
    default: op
  crazyonline.before:
    description: Shows which players has not been online
    default: op
  crazyonline.mode:
    description: Allow changing plugin mode
    default: op
  crazyonline.list:
    description: List all player accounts.
    default: op
  crazyonline.player.info:
    description: Allow viewing playerinfo.
    default: op
    children:
      crazyonline.player.info.self: true
      crazyonline.player.info.other: true
  crazyonline.player.info.self:
    description: Allow viewing own playerinfo.
    default: true
  crazyonline.player.info.other:
    description: Allow viewing playerinfo for other players.
    default: op
  crazyonline.player.delete:
    description: Allow deleting player data
    default: op