name: CrazyEnchanter
main: de.st_ddt.crazyenchanter.CrazyEnchanter
author: ST-DDT
version: 1.2.3
website: http://dev.bukkit.org/server-mods/crazyenchanter/
# requires CrazyCore v10.7.1 or later
depend: [CrazyCore]
description: >
            Enchant and repair your items.
commands:
  enchant:
    description: Enchant the item you held in your hand.
    usage: /<command> <enchantment:Enchantment> [level:Integer] [unsafe:Boolean]
  repair:
    description: Repair the item you held in your hand.
    usage: /<command> [level:Double]
  crazyenchanter:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
    aliases: [ce]
permissions:
  crazyenchanter.*:
    description: Access to all commands
    default: false
    children:
      crazyenchanter.enchant: true
      crazyenchanter.repair: true
  crazyenchanter.enchant:
    description: Allow enchanting your item.
    default: op
  crazyenchanter.repair:
    description: Allow repairing your item.
    default: op