name: CrazyLoginFilter
main: de.st_ddt.crazyloginfilter.CrazyLoginFilter
author: ST-DDT
version: 0.8
website: http://dev.bukkit.org/server-mods/crazyloginfilter/
# requires CrazyCore v10.5 or later
depend: [CrazyCore]
description: >
            CrazyLoginFilter protect your server with ip and connection filters for each player and the server itself.
depend: [CrazyCore]
commands:
  crazyloginfilter:
    description: Plugin Main Menu
    usage: /<command> [Subcommands...]
    aliases: [clf]
permissions:
  crazyloginfilter.*:
    description: Access to all commands
    default: false
    children:
      crazyloginfilter.admin: true
      crazyloginfilter.mode: true
      crazyloginfilter.warndatabase: true
  crazyloginfilter.admin:
    description: Allow changing account data for other players
    default: op
    children: 
      crazyloginfilter.mode: true
      crazyloginfilter.warndatabase: true
  crazyloginfilter.mode:
    description: Allow changing plugin mode
    default: op
  crazyloginfilter.warndatabase:
    description: Get informed if database connection fails
    default: op